---
kind: pipeline
type: docker
name: default

steps:
  - name: setup
    image: node:16
    when:
      event: push
    commands:
      - yarn --frozen-lockfile --ignore-scripts

  - name: lint
    image: node:16
    when:
      event: push
    commands:
      - yarn lint
      -
  - name: test
    image: node:16
    when:
      event: push
    commands:
      - yarn test

  - name: build
    image: node:16
    when:
      event: push
    commands:
      - apt-get update
      - apt-get install rsync -y
      - yarn build
