pipeline:
  setup:
    image: node:10
    when:
      event: push
    commands:
      - yarn --frozen-lockfile --ignore-scripts
  lint:
    image: node:10
    when:
      event: push
    commands:
      - yarn lint
  build:
    image: node:10
    when:
      event: push
    commands:
      - yarn build
