pipeline:
  setup:
    image: abakus/node-rsync:latest
    when:
      event: push
    commands:
      - yarn --frozen-lockfile --ignore-scripts
  lint:
    image: abakus/node-rsync:latest
    when:
      event: push
    commands:
      - yarn lint
  build:
    image: abakus/node-rsync:latest
    when:
      event: push
    commands:
      - yarn build
