---
kind: pipeline
type: docker
name: default

steps:
  - name: setup
    image: node:16
    when:
      event: push
    commands:
      - yarn --frozen-lockfile --ignore-scripts

  - name: lint
    image: node:16
    when:
      event: push
    commands:
      - yarn lint

  - name: Type check
    image: node:16
    when:
      event: push
    commands:
      - yarn check

  - name: test
    image: node:16
    when:
      event: push
    commands:
      - yarn test

  - name: build
    image: node:16
    when:
      event: push
    commands:
      - yarn build
